import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type { SkipperConfig } from "./types";
import { ADAPTERS } from "./providers/registry";
import { profilesDir, shellEnvPath } from "./paths";
import { defaultProfileName } from "./profiles";
import { writeFileAtomic } from "./fsutil";

/** ~/.skipper/env.sh: sourcing it from a shell rc makes skipr's per-provider
 * default profiles apply to plain `claude` / `codex` in new shells - the
 * system-default mechanism. Credentials are never copied between stores
 * (duplicating an OAuth chain breaks on the next refresh-token rotation);
 * this only points the provider at the default profile's home. */
export function writeShellEnv(config: SkipperConfig): void {
  const lines = [
    "# generated by skipr - do not edit (skipr rewrites this on 'Set as default')",
    "# source this from your shell rc:  source ~/.skipper/env.sh",
  ];
  for (const adapter of Object.values(ADAPTERS)) {
    const name = defaultProfileName(config, adapter.id);
    if (name === adapter.adoptedName) continue; // adopted home = the binary's own default
    lines.push(`export ${adapter.envVar}=${JSON.stringify(join(profilesDir(), name))}`);
  }
  writeFileAtomic(shellEnvPath(), lines.join("\n") + "\n");
}

const RC_FILES = [".zshrc", ".bashrc", ".bash_profile"];

/** Is env.sh already sourced from a shell rc? */
export function shellRcHooked(): boolean {
  for (const rc of RC_FILES) {
    try {
      if (readFileSync(join(homedir(), rc), "utf8").includes("skipper/env.sh")) return true;
    } catch {
      // rc file absent - fine
    }
  }
  return false;
}

export function shellSetupHint(): string | null {
  if (!existsSync(shellEnvPath()) || shellRcHooked()) return null;
  return `to apply outside skipr, add to your shell rc:  source ~/.skipper/env.sh`;
}
